on:
  pull_request:
    types: [ opened, reopened, synchronize, closed ]
env:
  PR_COMMIT_TAG: ${{ github.event.pull_request.head.sha }}
  MERGE_COMMIT_TAG: ${{ github.sha }}
jobs:
  
  # find the image in the repository tagged with this PR's commit
  # add the merge commit as an additional tag for a later deploy
  tag-image:
    runs-on: ubuntu-latest
    steps:
      - name: Add the merge commit tag
        if: github.event.pull_request.merged == true
        # run: echo "Merge commit is: $TAG"
        run: |
          echo "Adding merge commit tag $MERGE_COMMIT_TAG to the container image tagged with PR commit $PR_COMMIT_TAG"
