on: pull_request
env:
  TAG: ${{ github.event.pull_request.head.sha }}
jobs:
  
  get-commit:
    runs-on: ubuntu-latest
    steps:
      - name: echo commit
        run: echo $TAG

      - name: retag container on PR merge
        # if: github.event.pull_request.merged == true
        # run: echo "Merge commit is: $TAG"
        run: echo "Commits: ${{ github.events.commits }}"
