name: reset-develop-master
on:
  workflow_dispatch:
  schedule:
    # 8am ET Saturdays
    - cron: "0 12 * * SAT"
jobs:
  reset-develop:
    name: Reset develop branch to master
    runs-on: ubuntu-latest
    steps:
      - name: Reset develop
        uses: actions/checkout@v3
        with:
          ref: develop
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git reset --hard master
          git push -f
